#서버 설정
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
 
#뷰리졸버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/mediaproject/
      suffix: .jsp
#데이터소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: idbc:h2:tcp://localhost/~/test
    username: sa
    password: